# Generated by Django 5.1.5 on 2025-01-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=100, unique=True)),
                ('descripcion_cat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=100)),
                ('direccion_prov', models.TextField(blank=True, null=True)),
                ('telefono_prov', models.CharField(blank=True, max_length=15, null=True)),
                ('email_prov', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=100)),
                ('descripcion_prod', models.TextField(blank=True, null=True)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_prod', models.PositiveIntegerField(default=0)),
                ('codigo_barras_prod', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fk_id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('descripcion_movimiento', models.TextField(blank=True, null=True)),
                ('fk_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detalles', to='almacen.compra')),
                ('fk_id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='fk_id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.producto')),
                ('fk_id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detalles', to='almacen.venta')),
            ],
        ),
    ]
