# Generated by Django 5.1.5 on 2025-01-26 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_producto_fk_id_proveedor_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='descripcion_movimiento',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
